// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

String keyWeb = dotenv.env['API_KEY_WEB'] ?? '';
String keyMobile = dotenv.env['API_KEY_MOBILE'] ?? '';
String keyIos = dotenv.env['API_KEY_IOS'] ?? '';
String keyMac = dotenv.env['API_KEY_MAC'] ?? '';
String keyWindows = dotenv.env['API_KEY_WINDOWS'] ?? '';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: keyWeb,
    appId: '1:396084129750:web:32688cd4e796639c00fe77',
    messagingSenderId: '396084129750',
    projectId: 'flutter-kekerasan-seksual',
    authDomain: 'flutter-kekerasan-seksual.firebaseapp.com',
    storageBucket: 'flutter-kekerasan-seksual.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: keyMobile,
    appId: '1:396084129750:android:5fe8eb84173ed5a800fe77',
    messagingSenderId: '396084129750',
    projectId: 'flutter-kekerasan-seksual',
    storageBucket: 'flutter-kekerasan-seksual.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: keyIos,
    appId: '1:396084129750:ios:c9e1a902c332d5dd00fe77',
    messagingSenderId: '396084129750',
    projectId: 'flutter-kekerasan-seksual',
    storageBucket: 'flutter-kekerasan-seksual.firebasestorage.app',
    iosBundleId: 'com.example.pengaduan',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: keyMac,
    appId: '1:396084129750:ios:c9e1a902c332d5dd00fe77',
    messagingSenderId: '396084129750',
    projectId: 'flutter-kekerasan-seksual',
    storageBucket: 'flutter-kekerasan-seksual.firebasestorage.app',
    iosBundleId: 'com.example.pengaduan',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: keyWindows,
    appId: '1:396084129750:web:81f66c6084db221c00fe77',
    messagingSenderId: '396084129750',
    projectId: 'flutter-kekerasan-seksual',
    authDomain: 'flutter-kekerasan-seksual.firebaseapp.com',
    storageBucket: 'flutter-kekerasan-seksual.firebasestorage.app',
  );
}
